version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset:
    run: databuilder:v0
      generate-dataset analysis/dataset_definition.py --output output/dataset.csv
      
    outputs:
      highly_sensitive:
        cohort: output/dataset.csv

  generate_dummy_dataset:
    run: databuilder:v0
      generate-dataset analysis/simple_dataset_definition.py --output output/dataset_2.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_2.csv