version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset_cohortextractor:
    run: >
      cohortextractor:latest generate_cohort 
        --study-definition study_definition
        --index-date-range '2022-09-25 to 2022-09-25 by week' 
        --output-dir 'output'
        --output-file "output/dataset_cohortextractor.csv"
        --output-format csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_cohortextractor_2022-09-25.csv

  generate_dataset_ehrql:
    run: >
      databuilder:v0
        generate-dataset analysis/dataset_definition.py 
        --output output/dataset_ehrql_2022-09-25.csv
        --dummy-tables dummy_data
    outputs:
      highly_sensitive:
        cohort: output/dataset_ehrql_2022-09-25.csv
 
  # calculate_dataset_diff:
  #   run: >
  #     r:latest analysis/dataset_diff.R
  #   needs:
  #     - generate_dataset_cohortextractor
  #     - generate_dataset_ehrql
  #   outputs:
  #     moderately_sensitive:
  #       cohort: output/diff/dataset_diff_summary.csv
