version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset:
    run: databuilder:v0
      generate-dataset analysis/dataset_definition.py --output output/dataset.csv
      --dummy-tables dummy_data
    outputs:
      highly_sensitive:
        cohort: output/dataset.csv

  generate_dataset_report:
    run: >
      dataset-report:v0.0.26
        --input-files output/dataset.csv
        --output-dir output
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        dataset_report: output/dataset.html
